### ISSUE TITLE
webpack3.0打包 居然有18M

### ISSUE THREAD

**Issue by leonwgc** [alibaba/react-intl-universal#19] opened 2017-07-22 08:25 UTC

**Comment by cwtuan** [comment] 2017-07-22 14:59
Thanks for reporting this issue. 
duplicate of #17. Close this.

**Closed** 2017-07-22 15:00 UTC

**Comment by cwtuan** [comment] 2017-08-15 05:46
@leonwgc 
Please upgrade to v1.3.4 to fix build issue.
